FormKey: 227720:Starfield.esm
EditorID: Clothes_Akila_Security
FormVersion: 558
ObjectBounds:
  First: -0.26464844, -0.20669045, 0.0009460449
  Second: 0.26416016, 0.20712791, 0.23083496
ODTY: 0
Transforms:
  InventoryIcon: 0E7EB9:Starfield.esm
Name:
  TargetLanguage: English
  Value: Akila Security Uniform
WorldModel:
  Male:
    File: SetDressing\OutfitContainer01.nif
  Female:
    File: SetDressing\OutfitContainer01.nif
FirstPersonFlags: 40
Race: 00347D:Starfield.esm
Keywords:
- 1F0A14:Starfield.esm
- 0E048C:Starfield.esm
- 2B55A6:Starfield.esm
Description:
  TargetLanguage: English
  Value: ''
Armatures:
- AddonIndex: 0
  AddonModel: 12B4B7:Starfield.esm
- AddonIndex: 0
  AddonModel: 12B4B6:Starfield.esm
- AddonIndex: 0
  AddonModel: 12B4B5:Starfield.esm
- AddonIndex: 0
  AddonModel: 36E3DC:Starfield.esm
Value: 225
Weight: 2.1
Unused: 0x000000
Resistances:
- DamageType: 060A81:Starfield.esm
- DamageType: 023190:Starfield.esm
AttachParentSlots:
- 022821:Starfield.esm
ObjectTemplates:
- Default: True
  Includes:
  - Mod: 1C5A9E:Starfield.esm
    DontUseAll: True
  - Mod: 13DDE2:Starfield.esm
    DontUseAll: True
  Properties:
  - MutagenObjectType: ObjectModFormLinkIntProperty<Armor+Property>
    Property: 14
    Record: 0CC5DD:Starfield.esm
